### ISSUE TITLE
[BUG]  7.4.1  states premium@1.19.0-rc.3.

### ISSUE THREAD

**Issue by duttonw** [formio/enterprise-release#2]
Hi,

I don't believe you used a release candidate for an official release.

Should it not be on the 1.18.x pipeline?

https://github.com/formio/enterprise-release/blob/master/API-Server-Change-Log.md (updated 5 days ago  https://github.com/formio/enterprise-release/commit/a85b772a71f91b89c66cd163a0f1a085a56d5908 )
October 7th, 2022 Release
API Server Version 7.4.1
Included Correlated Libraries:
portal@7.4.1
formviewpro@1.99.1
formmanager@1.99.1
formiojs@4.14.9
**premium@1.19.0-rc.3**
offline@4.2.0
formio@2.5.2
uswds@2.4.8-rc.1
vpat@2.4.3-rc.1

On the private npmjs repo it has these versions only.

1.18.6 5 days ago
1.18.6-rc.8 a month ago
1.18.6-rc.7 a month ago
1.18.6-rc.6 a month ago
1.18.6-rc.5 a month ago
1.18.6-rc.4 2 months ago
1.18.6-rc.3 2 months ago
1.18.6-rc.2 2 months ago
1.18.6-rc.1 2 months ago
1.18.5 2 months ago
1.18.5-rc.5 2 months ago
1.18.5-rc.4 3 months ago
1.18.5-rc.3 3 months ago
1.18.5-rc.2 3 months ago
1.18.5-rc.1 3 months ago
1.18.4 4 months ago
1.18.4-rc.2 4 months ago
1.18.4-rc.1 5 months ago
1.18.3 5 months ago
1.18.3-rc.1 5 months ago
1.18.2 5 months ago
1.19.0-rc.3 5 months ago
1.18.2-rc.1 5 months ago
1.19.0-rc.2 6 months ago
1.18.1 7 months ago

**Comment by lane-formio** [comment]
Thanks for the catch!
