### ISSUE TITLE
[BUG] @formio/premium 1.19.x onwards missing changelog

### ISSUE THREAD

**Issue by duttonw** [formio/enterprise-release#4]
in @formio/premium 1.18.4  included a change log. 1.19.1 onwards does not.
It was located at @formio/premium/Changelog.md

**Comment by duttonw** [comment]
@lane-formio Are you able to get the change log working again like it did 1+ years ago?

**Comment by lane-formio** [comment]
All tickets related to any of our dependent libraries (such as @formio/premium) are now included in the [API / PDF Server Changelog](https://github.com/formio/enterprise-release/blob/master/API-Server-Change-Log.md)
If there are any specific issues/tickets you are tracking for release you should be able to locate them there, or feel free to contact support@form.io if you are looking for an update on any tickets that haven't been released yet.
